# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BxEukWsktw3qSA9jNxOaMV0PMCmEw-Ea

## Q1(a): PDF Reading and Text Extraction
"""

from PyPDF2 import PdfReader

pdf_path = '/content/mcs.pdf'

all_text = []
try:
    reader = PdfReader(pdf_path)
    num_pages = len(reader.pages)

    print(f"Total number of pages in the PDF: {num_pages}")

    for i in range(num_pages):
        page = reader.pages[i]
        text = page.extract_text()
        if text:
            all_text.append(text)

    full_text_content = " ".join(all_text)

    print("\nSample extracted text (first 500 characters):\n")
    print(full_text_content[:500])

except FileNotFoundError:
    print(f"Error: The file '{pdf_path}' was not found. Please upload the PDF or provide the correct path.")
except Exception as e:
    print(f"An error occurred while reading the PDF: {e}")

"""**Q1(B): Applying Regex**"""

import re

# extracted text into lowercase.
processed_text = full_text_content.lower()
print("Text after converting to lowercase (first 500 characters):\n")
print(processed_text[:500])

# Removing numbers using Regex.
number_pattern = r'\d+'
processed_text = re.sub(number_pattern, '', processed_text)
print("\nText after removing numbers (first 500 characters):\n")
print(processed_text[:500])
print(f"Regex pattern used for numbers: {number_pattern}")


special_symbol_pattern = r'[^a-zA-Z\s]'
processed_text = re.sub(special_symbol_pattern, '', processed_text)
print("\nText after removing special symbols (first 500 characters):\n")
print(processed_text[:500])
print(f"Regex pattern used for special symbols: {special_symbol_pattern}")

extra_spaces_pattern = r'\s+'
processed_text = re.sub(extra_spaces_pattern, ' ', processed_text).strip()
print("\nText after removing extra spaces (first 500 characters):\n")
print(processed_text[:500])
print(f"Regex pattern used for extra spaces: {extra_spaces_pattern}")


import string
punctuation_pattern = f"[{re.escape(string.punctuation)}]"
processed_text = re.sub(punctuation_pattern, '', processed_text)
print("\nText after removing punctuation (first 500 characters):\n")
print(processed_text[:500])
print(f"Regex pattern used for punctuation: {punctuation_pattern}")

import nltk
from nltk.corpus import stopwords


try:
    nltk.data.find('corpora/stopwords')
except LookupError:
    nltk.download('stopwords')

try:
    nltk.data.find('tokenizers/punkt')
except LookupError:
    nltk.download('punkt')

try:
    # nltk.word_tokenize might implicitly need punkt_tab
    nltk.data.find('tokenizers/punkt_tab')
except LookupError:
    nltk.download('punkt_tab')

# 6. Tokenize the text into words.
words = nltk.word_tokenize(processed_text)
print(f"\nTotal words after tokenization: {len(words)}")
print(f"Sample tokenized words (first 20): {words[:20]}")

# 7. Apply stop word removal.
stop_words = set(stopwords.words('english'))
filtered_words = [word for word in words if word not in stop_words]

# 8. Show the count of total stop words found in the text.
total_stop_words_found = len(words) - len(filtered_words)
print(f"\nTotal stop words found and removed: {total_stop_words_found}")

# 9. Show the count of valid words after stop word removal.
valid_words_count = len(filtered_words)
print(f"Total valid words after stop word removal: {valid_words_count}")
print(f"Sample valid words (first 20): {filtered_words[:20]}")

from nltk.stem import PorterStemmer, WordNetLemmatizer

# Download necessary NLTK data for stemming and lemmatization
try:
    nltk.data.find('corpora/wordnet')
except LookupError:
    nltk.download('wordnet')
try:
    nltk.data.find('corpora/omw-1.4')
except LookupError:
    nltk.download('omw-1.4')

# 10. Apply stemming on valid words.
stemmer = PorterStemmer()
stemmed_words = [stemmer.stem(word) for word in filtered_words]
print(f"\nSample stemmed words (first 20): {stemmed_words[:20]}")

# 11. Apply lemmatization on valid words.
lemmatizer = WordNetLemmatizer()
lemmatized_words = [lemmatizer.lemmatize(word) for word in filtered_words]
print(f"\nSample lemmatized words (first 20): {lemmatized_words[:20]}")

"""## Q1(c): Feature Extraction

### One Hot Encoding


"""

from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

lemmatized_text_document = " ".join(lemmatized_words)

vectorizer = CountVectorizer(binary=True)

# Fit and transform the document
one_hot_matrix = vectorizer.fit_transform([lemmatized_text_document])

# Get feature names (words in the vocabulary)
feature_names = vectorizer.get_feature_names_out()

print(f"Total unique words in vocabulary (features): {len(feature_names)}")


one_hot_df = pd.DataFrame(one_hot_matrix.toarray(), columns=feature_names)

print("\nSample One-Hot Encoded Output (first 10 unique words showing presence in the document):\n")
# Displaying the first row  and a sample of columns
print(one_hot_df.iloc[0, :20].T.to_markdown(numalign="left", stralign="left"))

"""### TF-IDF"""

from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

tfidf_vectorizer = TfidfVectorizer()

tfidf_matrix = tfidf_vectorizer.fit_transform([lemmatized_text_document])

tfidf_feature_names = tfidf_vectorizer.get_feature_names_out()

print(f"Total unique words (TF-IDF features): {len(tfidf_feature_names)}")

tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf_feature_names)

print("\nSample TF-IDF Feature Names (first 20):\n")
print(list(tfidf_feature_names[:20]))

print("\nSample TF-IDF Values (first 20 features for the document):\n")
print(tfidf_df.iloc[0, :20].T.to_markdown(numalign="left", stralign="left"))

import plotly.express as px
import pandas as pd

tfidf_scores = tfidf_df.iloc[0].to_frame(name='TFIDF_Score')
tfidf_scores['Word'] = tfidf_scores.index

tfidf_scores = tfidf_scores.sort_values(by='TFIDF_Score', ascending=False)

top_n_words = 100
plot_data = tfidf_scores.head(top_n_words)

fig = px.scatter(
    plot_data,
    x='Word',
    y='TFIDF_Score',
    title=f'Top {top_n_words} TF-IDF Scores for Words in Document',
    labels={
        'Word': 'Word',
        'TFIDF_Score': 'TF-IDF Score'
    },
    hover_name='Word'
)

fig.update_layout(xaxis_tickangle=-45)

fig.show()